image: docker:stable

variables:
  PROJECT: 4xtreme
  GROUP: shared
  REGISTRY: registry.eternal-cloud.synology.me
  
stages:
- build
- push

before_script:
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY

build:
  stage: build
  script:
    - docker pull $REGISTRY/$GROUP/$PROJECT:latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $REGISTRY/$GROUP/$PROJECT:$CI_COMMIT_SHA
      .
    - docker push $REGISTRY/$GROUP/$PROJECT:$CI_COMMIT_SHA

push:
  stage: push
  script:
    - docker pull $REGISTRY/$GROUP/$PROJECT:$CI_COMMIT_SHA
    - docker tag $REGISTRY/$GROUP/$PROJECT:$CI_COMMIT_SHA $REGISTRY/$GROUP/$PROJECT:latest
    - docker push $REGISTRY/$GROUP/$PROJECT:latest
  only:
    - main
